"""Generates the EU261 claim-pack PDF: a ready-to-send claim letter citing Reg 261/2004.

Security: ALL user-supplied text is escaped before being placed into reportlab
Paragraph markup (which parses a subset of HTML). User input is untrusted data.
"""
from __future__ import annotations

from xml.sax.saxutils import escape as xml_escape

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

DISCLAIMER = ("This claim pack was generated by an automation template and is provided "
              "for informational purposes only. It is NOT legal advice. Consider consulting "
              "a qualified lawyer before filing, especially where extraordinary circumstances "
              "are disputed.")


def _u(value) -> str:
    """Escape untrusted user text for Paragraph markup."""
    return xml_escape(str(value or ""))


def build_pdf(claim: dict, verdict: dict, path: str) -> str:
    """Build the claim-pack PDF. `claim` is the stored payload, `verdict` the eligibility verdict."""
    doc = SimpleDocTemplate(path, pagesize=A4, topMargin=25 * mm, bottomMargin=25 * mm,
                            leftMargin=25 * mm, rightMargin=25 * mm)
    styles = getSampleStyleSheet()
    body = styles["Normal"]
    story = []
    add = story.append

    add(Paragraph("<b>EU261/2004 Flight Compensation Claim</b>", styles["Title"]))
    add(Spacer(1, 6 * mm))
    add(Paragraph(xml_escape(DISCLAIMER), body))
    add(Spacer(1, 6 * mm))

    p = claim  # payload dict
    v = verdict
    delay_txt = (f"arrived with a delay of approximately {p['arrival_delay_h']:.1f} hours"
                 if p.get("arrival_delay_h") else f"was {str(p.get('disruption', '')).replace('_', ' ')}")
    rows = [
        ("Passenger", f"{_u(p.get('passenger_name'))} ({_u(p.get('passenger_email'))})"),
        ("Airline", _u(p.get("airline"))),
        ("Flight", f"{_u(p.get('flight_number'))} on {_u(p.get('flight_date'))}"),
        ("Route", f"{_u(v['from']['iata'])} ({_u(v['from'].get('name'))}) → "
                  f"{_u(v['to']['iata'])} ({_u(v['to'].get('name'))})"),
        ("Disruption", _u(p.get("disruption"))),
        ("Scheduled arrival", _u(p.get("scheduled_arrival")) or "—"),
        ("Actual arrival", _u(p.get("actual_arrival")) or "—"),
        ("Compensation sought", f"EUR {v['compensation_eur']} (Regulation (EC) No 261/2004, Article 7)"),
    ]
    t = Table([[Paragraph(f"<b>{_u(k)}</b>", body), Paragraph(val, body)] for k, val in rows],
              colWidths=[45 * mm, 120 * mm])
    t.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP"),
                           ("LINEBELOW", (0, 0), (-1, -1), 0.5, colors.grey)]))
    add(t)
    add(Spacer(1, 8 * mm))

    add(Paragraph("<b>Draft claim letter</b>", styles["Heading2"]))
    letter = (
        f"Dear {_u(p.get('airline')) or 'Sir/Madam'},<br/><br/>"
        f"I am writing to claim compensation under Regulation (EC) No 261/2004 for flight "
        f"{_u(p.get('flight_number'))} on {_u(p.get('flight_date'))} from "
        f"{_u(v['from']['iata'])} to {_u(v['to']['iata'])}.<br/><br/>"
        f"The flight {_u(delay_txt)} at my final destination. Under Article 7 of the "
        f"Regulation, I request your assessment and payment of <b>EUR {v['compensation_eur']}</b>.<br/><br/>"
        f"I will provide the booking and travel evidence required to assess my claim. Please pay any amount owed "
        f"to the account details I will provide on request, or contact me at "
        f"{_u(p.get('passenger_email'))}.<br/><br/>"
        f"Please explain any refusal and the applicable complaint or appeal procedure.<br/><br/>"
        f"Yours faithfully,<br/>{_u(p.get('passenger_name'))}"
    )
    add(Paragraph(letter, body))
    add(Spacer(1, 8 * mm))

    add(Paragraph("<b>Eligibility basis (generated)</b>", styles["Heading2"]))
    for r in v["reasons"]:
        add(Paragraph(f"• {_u(r)}", body))
    add(Spacer(1, 6 * mm))
    add(Paragraph(xml_escape(DISCLAIMER), body))

    doc.build(story)
    return path
