"""Demand-letter PDF generation.

The letter cites the employee's state statute and payment deadline. It is
template automation, NOT legal advice, and it is NEVER sent by the service:
the PDF is generated for the user, who sends it themselves.

Generated only when the case is overdue; the API enforces that gate.
"""
from datetime import date
from pathlib import Path

from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

from sanitize import clean_text, money

BASE_DIR = Path(__file__).resolve().parent
LETTERS_DIR = BASE_DIR / "data" / "letters"

DISCLAIMER = (
    "This letter was generated by automated template software and is not legal "
    "advice. It does not create an attorney-client relationship. Consider "
    "consulting a licensed employment attorney in your state."
)


def generate_demand_letter(case: dict, law: dict) -> Path:
    """Render the demand letter PDF for an overdue case. Returns the PDF path.

    All user-supplied fields are sanitized: treated as untrusted data and
    stripped of control characters / bounded in length before rendering.
    """
    LETTERS_DIR.mkdir(parents=True, exist_ok=True)
    path = LETTERS_DIR / f"demand_letter_{case['id']}.pdf"

    # Sanitize every user-supplied value that lands in the document.
    employer_name = clean_text(case["employer_name"], 120)
    employer_address = clean_text(case.get("employer_address") or "", 300)
    employee_name = clean_text(case["employee_name"], 120)
    employee_email = clean_text(case.get("employee_email") or "", 120)
    forwarding_address = clean_text(case.get("forwarding_address") or "", 300)
    pay_period = clean_text(case.get("pay_period") or "final pay period", 80)
    termination_type = clean_text(case.get("termination_type") or "", 20)
    last_day = clean_text(case.get("last_day_worked") or "", 20)
    state_name = clean_text(law.get("state_name") or "", 60)
    statute = clean_text(law.get("statute") or "the applicable state wage-payment statute", 160)
    penalty = clean_text(law.get("penalty_note") or "", 300)
    deadline = clean_text(case.get("deadline") or "", 20)
    overdue_days = int(law.get("days_overdue", 0) or 0)
    today_str = date.today().strftime("%B %d, %Y")

    c = canvas.Canvas(str(path), pagesize=LETTER)
    w, h = LETTER
    left, right = inch, w - inch
    y = h - inch

    def line(text: str, size: int = 11, bold: bool = False, gap: int = 16):
        nonlocal y
        c.setFont("Helvetica-Bold" if bold else "Helvetica", size)
        c.drawString(left, y, text)
        y -= gap

    def para(text: str, size: int = 11, gap_after: int = 10):
        nonlocal y
        c.setFont("Helvetica", size)
        max_w = right - left
        words, cur = text.split(), ""
        for word in words:
            trial = f"{cur} {word}".strip()
            if c.stringWidth(trial, "Helvetica", size) > max_w and cur:
                c.drawString(left, y, cur)
                y -= 15
                cur = word
            else:
                cur = trial
        if cur:
            c.drawString(left, y, cur)
            y -= 15
        y -= gap_after

    line("DEMAND FOR UNPAID FINAL WAGES", 16, bold=True, gap=26)
    line(today_str, gap=22)

    line("VIA CERTIFIED MAIL / EMAIL", 10, bold=True, gap=20)
    line(employer_name, 12, bold=True, gap=16)
    for addr_line in employer_address.splitlines():
        line(addr_line, gap=15)
    y -= 8

    line(f"Re: Unpaid final wages owed to {employee_name}", 11, bold=True, gap=20)

    para(f"Dear {employer_name}:")
    para(
        f"This letter concerns unpaid final wages owed to {employee_name}, "
        f"whose last day of work was {last_day} "
        f"(separation type: {termination_type})."
    )
    para(
        f"Under {statute} ({state_name}), final wages were due no later "
        f"than {deadline}. As of the date of this letter, {overdue_days} day(s) have "
        f"passed since that deadline and {money(case['wages_owed_cents'])} in earned "
        f"wages for the pay period '{pay_period}' "
        f"remains unpaid."
    )
    para(
        "This is a formal demand for immediate payment of all wages owed, in full, "
        "to the forwarding address below."
    )
    if penalty:
        para(f"Note: {penalty}")
    para(
        "If full payment is not received promptly, the employee reserves the right "
        "to file a wage claim with the state labor department and to pursue all "
        "remedies available under law, which may include penalties, interest, and "
        "attorney's fees."
    )
    para("Forwarding address for payment:")
    for addr_line in forwarding_address.splitlines():
        line(f"    {addr_line}", gap=15)
    y -= 10
    line("Sincerely,", gap=28)
    line(employee_name, bold=True, gap=16)
    if employee_email:
        line(employee_email, gap=20)

    y -= 10
    c.setFont("Helvetica-Oblique", 8.5)
    max_w = right - left
    words, cur = DISCLAIMER.split(), ""
    for word in words:
        trial = f"{cur} {word}".strip()
        if c.stringWidth(trial, "Helvetica-Oblique", 8.5) > max_w and cur:
            c.drawString(left, y, cur)
            y -= 12
            cur = word
        else:
            cur = trial
    if cur:
        c.drawString(left, y, cur)

    c.showPage()
    c.save()
    return path
