#!/usr/bin/env python3
"""Print a complete nginx configuration; never read or print credentials."""
import argparse
import re

SLUGS = ('deposit-recovery', 'eu261-flight-comp', 'subscription-slayer', 'bill-negotiator',
         'final-paycheck', 'class-action-cash', 'unclaimed-property', 'moving-concierge',
         '401k-match', 'medical-bill-fighter')


def render(domain, tls=False):
    if not re.fullmatch(r'[a-z0-9](?:[a-z0-9.-]{0,251}[a-z0-9])?', domain):
        raise ValueError('DOMAIN must be a DNS hostname without a scheme, path, or port')
    lines = ['# Generated by backend/deploy/render-nginx.py',
             'limit_req_zone $binary_remote_addr zone=qull_std:10m rate=120r/m;',
             'limit_req_zone $binary_remote_addr zone=qull_money:10m rate=20r/m;',
             'limit_req_status 429;']
    if tls:
        lines.extend(['server {', '    listen 80;', f'    server_name {domain};',
                      f'    return 308 https://{domain}$request_uri;', '}'])
    lines.extend(['server {', '    listen 443 ssl;' if tls else '    listen 80;',
                  f'    server_name {domain};'])
    if tls:
        lines.extend([f'    ssl_certificate /etc/letsencrypt/live/{domain}/fullchain.pem;',
                      f'    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;',
                      '    ssl_protocols TLSv1.2 TLSv1.3;',
                      '    add_header Strict-Transport-Security "max-age=31536000" always;'])
    lines.extend(['    client_max_body_size 1000000;', '    client_body_timeout 15s;',
                  '    server_tokens off;', '    add_header X-Content-Type-Options nosniff always;',
                  '    location / { return 404; }'])
    for index, slug in enumerate(SLUGS):
        lines.append(f'    location = /{slug} {{ return 308 /{slug}/; }}')
        for path, upstream, streaming in ((f'/{slug}/', f'http://127.0.0.1:{8471+index}/', False),
                                         (f'= /{slug}/mcp', f'http://127.0.0.1:{8571+index}/mcp', True),
                                         (f'/{slug}/mcp/', f'http://127.0.0.1:{8571+index}/mcp/', True)):
            lines.extend([f'    location {path} {{',
                          f'        limit_req zone={"qull_money" if streaming else "qull_std"} burst=20 nodelay;',
                          f'        proxy_pass {upstream};', '        proxy_http_version 1.1;',
                          '        proxy_set_header Host $host;',
                          '        proxy_set_header Authorization $http_authorization;',
                          '        proxy_set_header X-Real-IP $remote_addr;',
                          '        proxy_set_header X-Forwarded-For $remote_addr;',
                          '        proxy_set_header X-Forwarded-Proto $scheme;',
                          '        proxy_set_header X-Platform-User-Id "";',
                          '        proxy_set_header X-Dev-User-Id "";'])
            if streaming:
                lines.extend(['        proxy_buffering off;', '        proxy_read_timeout 300s;',
                              '        proxy_send_timeout 300s;'])
            else:
                lines.append('        proxy_read_timeout 60s;')
            lines.append('    }')
    lines.append('}')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--domain', required=True)
    parser.add_argument('--tls', action='store_true')
    args = parser.parse_args()
    print(render(args.domain, args.tls), end='')
