"""Statute-citing demand letter generation (PDF)."""
import re
from datetime import date
from fpdf import FPDF
from .laws import get_state
from .engine import compute_deadline

# Strip control characters from user-supplied text before rendering it into
# the PDF. User input is untrusted data: it is printed verbatim as text
# (never interpreted as markup or instructions).
_CONTROL_CHARS = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")


def sanitize(text) -> str:
    return _CONTROL_CHARS.sub("", str(text or ""))


def letter_body(case: dict, law: dict, deadline_iso: str, days_overdue: int) -> str:
    tenant_name = sanitize(case["tenant_name"])
    tenant_addr = sanitize(case["tenant_forwarding_address"])
    landlord_name = sanitize(case["landlord_name"])
    landlord_addr = sanitize(case["landlord_address"])
    rental_addr = sanitize(case["rental_address"])
    move_out = sanitize(case["move_out"])
    mult = law["penalty_multiple"]
    if mult and mult > 1:
        penalty_line = (
            f"Please be advised that under {law['statute']}, a landlord who retains a "
            f"security deposit in bad faith may be liable for up to {mult} times the deposit "
            f"amount, or up to ${case['deposit'] * mult:,.2f}, plus court costs and attorney's fees "
            f"where applicable."
        )
    else:
        penalty_line = (
            f"Please be advised that under {law['statute']}, additional statutory damages, "
            f"court costs, and attorney's fees may apply to the wrongful retention of a "
            f"security deposit."
        )

    return f"""{tenant_name}
{tenant_addr}

{date.today().strftime('%B %d, %Y')}

{landlord_name}
{landlord_addr}

Re: Demand for return of security deposit
   Property: {rental_addr}
   Tenancy ended: {move_out}

Dear {landlord_name},

I am writing to demand the immediate return of my security deposit in the amount of \
${case['deposit']:,.2f} for the above-referenced property.

Under {law['statute']}, you were required to return my deposit or provide a written \
itemized statement of deductions by {deadline_iso}. That deadline passed {days_overdue} \
day(s) ago, and I have received neither the deposit nor an itemization.

I demand payment of the full ${case['deposit']:,.2f} within ten (10) days of the date \
of this letter.

{penalty_line}

If I do not receive payment within ten days, I intend to pursue all remedies available \
under {law['statute']}, including filing in small claims court, without further notice.

Sincerely,

{tenant_name}

---
This letter was generated by an automated tool and is not legal advice. \
Verify the cited statute against current {law['state']} law before sending."""


def build_pdf(case: dict, path: str) -> str:
    law = get_state(case["state"])
    dl = compute_deadline(case["state"], date.fromisoformat(case["move_out"]),
                          date.fromisoformat(case["forwarding_date"]) if case.get("forwarding_date") else None)
    deadline = date.fromisoformat(dl["deadline"])
    overdue = (date.today() - deadline).days

    pdf = FPDF(format="Letter")
    pdf.set_auto_page_break(auto=True, margin=25)
    pdf.add_page()
    pdf.set_font("Helvetica", size=11)
    pdf.multi_cell(0, 6, letter_body(case, law, deadline.strftime("%B %d, %Y"), overdue))
    pdf.output(path)
    return path
